title: Variable Spacing docs
email: gustavo@hipertipo.com
description: Variable Spacing docs
baseurl: ""
url: https://hipertipo.gitlab.io/VariableSpacing/

markdown: kramdown

collections:
  topics:
    output: true
    permalink: /:path/
  reference:
    output: true
    permalink: /reference/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/

version: 0.1.4

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock

jekyll_tidy:
  exclude: []
  # ignore_env: development
  compress_html: false
